import type { Metadata } from "next";
import "./globals.css";
import { Web3Provider } from "@/context/Web3Context";
import { TokenProvider } from "@/context/TokenContext";
import { ToastContainer } from "react-toastify";
import { VolumeProvider } from "@/context/VolumeContext";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   <html lang="en">
      <body>
        <Web3Provider>
          <TokenProvider>
            <VolumeProvider>
            {children}
             <ToastContainer position="top-right" autoClose={4000} pauseOnHover />
</VolumeProvider>
          </TokenProvider>
        </Web3Provider>
      </body>
    </html>
  );
}
